### ISSUE TITLE
Add support for query Dashboard Variables

### ISSUE THREAD

**Issue by Jayclifford345** [influxdata/grafana-flightsql-datasource#80]
Currently, when trying to use a  FlightSQL query as a dashboard variable there is no UI component to make the query.

A great example of this is when we want to filter by the host. We could use a query like:
```
SELECT DISTINCT host FROM cpu
```

Currently, there just shows a regex text box.
<img width="961" alt="Screenshot 2023-02-01 at 12 45 15" src="https://user-images.githubusercontent.com/45856600/216047577-2827ffaa-574b-4a19-8734-89abb53740a5.png">

**Comment by helenosheaa** [comment]
So we currently have support for templating variables in the dashboard view. Eg I know the code I want to filter on is GBP so I can set that as a variable and then insert it into a query using ${code} here after creation in the dashboard.

<img width="888" alt="Screen Shot 2023-02-01 at 8 23 25 AM" src="https://user-images.githubusercontent.com/38860767/216055595-d4c73925-f8f8-424c-a554-22f0bfef8e60.png">

for query support I'm guessing it needs to have a query input box rather than just the regex like what's seen in the postgres plugin here?

<img width="1003" alt="Screen Shot 2023-02-01 at 8 27 30 AM" src="https://user-images.githubusercontent.com/38860767/216056098-27533201-474d-495a-b182-1ec14dc6fd74.png">

I'll do some research into how to achieve that as currently I'm not editing the dashboarding view its all just out of the box from grafana. I'll make sure I tag this issue when I pull it into a sprint :)

**Comment by jaredmcqueen** [comment]
@helenosheaa that templating view you mentioned earlier -- you have to type in the "GBP" right?

Variables are a killer feature of Grafana Dashboards, will def be following this issue.  Let me know how I can help.

**Comment by helenosheaa** [comment]
@jaredmcqueen correct! if this is a feature you wanted to start implementing we accept contributions from the community as well :)

**Comment by philmen1** [comment]
+1 for query support :)

**Comment by gpinkos** [comment]
Here is how I set up FlightSQL to use a variable where multiple choices can be selected:
![image](https://github.com/influxdata/grafana-flightsql-datasource/assets/97072938/6eba2c38-b308-4459-9f3b-3c5f43ed8c00)
Query:
`SELECT *
FROM "ElectricPowerOperations"
WHERE
"type" IN ('Demand') AND "region" IN (${region})
AND
$__timeRange(time)`
![variables](https://github.com/influxdata/grafana-flightsql-datasource/assets/97072938/0092f5c4-b3eb-43d8-bd0a-e44d883f671e)

**Comment by tieandrews** [comment]
+1 for query variable support, our use case has multiple tests runover a period and would like to be able to select/deselect test IDs in the window to filter down visualizations.

**Comment by rab-oli** [comment]
This is a pretty big feature that's missing from the plulgin. It renders what I'm trying to do impossible. If I knew where to start I'd jump in and help fix it.

**Comment by ShadeInteractive** [comment]
The problem is the same for us, we have to set our build number dropdown variable from the database iteslf.

Would you have any idea if it's gonna come at any point? It's clearly a blocking issue for us.

**Comment by garylfowler** [comment]
fyi:  Our friends at Grafana have been working on adding SQL support to the official Grafana InfluxDB plug-in over the past few months.  They current projection is for it to be available sometime in Q1, maybe as early as January.  It is likely to have better dashboard variable support than this community Flight-SQL plug-in.  So you may have another option soon.
